# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: interface                # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Plugin zur Steuerung von Amazon Echo Geräten Zugriff via Web-Browser API und Cookie'
        en: 'Plugin to remote control Echo Show/Spot/Fire'
    maintainer: AndreK
    tester: henfri
    documentation: https://github.com/Andrek01  # url of documentation (wiki) page    
    version: 1.0.0                              # Plugin version
    sh_minversion: 1.5.2                        # minimum shNG version to use this plugin
    multi_instance: False                       # plugin supports multi instance
    classname: AlexaRc4shNG                     # class containing the plugin
    keywords: Alexa Amazon Remote Control
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1021150-amazon-alexa-plugin
    state: develop                   # State of the Plugin
    restartable: True                # Plugin is restartable 

plugin_functions: NONE               # the Plugin provides no public functions
logic_parameters: NONE               # No logic parameters for this plugin
item_structs: NONE                   # no item structure needed
item_attributes:
    # Definition of item attributes defined by this plugin
    alexa_cmd_XX:
        type: str
        mandatory: True
        description:
            de: 'String um die Befehle zu definieren'
            en: 'Alexa device name to get acces to the device'  

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    cookiefile:
        type: str
        default: ''
        description:
            de: 'Cookiefile mit komplettem Pfad'
            en: 'Cookiefile with complete path'
    host:
        type: str
        default: ''
        description:
            de: 'Amazon-Host z.b. alexa.amazon.de ohne Protokoll (https)'
            en: 'Amazon-Host a.e. alexa.amazon.de without protocoll (https)'

